ticket/urls.py
from django.conf.urls import url
from .import views
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^test/$', views.TestingView.as_view(), name='test'),
    url(r'^pdf/$', views.GenerateView.as_view(), name='pdf'),
    url(r'^list/$', views.TicketView.as_view(), name='list'),
    url(r'^pending/$', views.PendingStatusView.as_view(), name='pending'),
    url(r'^solved/$', views.SolvedStatusView.as_view(), name='solved'),
    url(r'^closed/$', views.ClosedStatusView.as_view(), name='closed'),
    url(r'^(?P<pk>\d+)/detail/$', views.TicketDetailView.as_view(),
        name='detail'),
    url(r'^(?P<pk>\d+)/update/$', views.TicketupdateView.as_view(),
        name='update'),
    url(r'^(?P<pk>\d+)/comment/$', views.TicketCommentView.as_view(),
        name='comment'),
    url(r'^$', 'django.contrib.auth.views.login',
        {'template_name': 'base1.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'base.html'}, name='logout'),
    url(r'^register/$', CreateView.as_view(template_name='registration/register.html',form_class=UserCreationForm, success_url='/ticket/'), name='register'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ticket/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

from django.utils import timezone


CHOICE = (
    ('PENDING', 'PENDING'),
    ('SOLVED', 'SOLVED'),
    ('CLOSED', 'CLOSED')
)


class Ticket(models.Model):
    title = models.CharField(max_length=50)
    created = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(User)
    ticket_id = models.IntegerField(blank=True)
    body = models.TextField()
    status = models.CharField(
        max_length=40,
        choices=CHOICE, default='PENDING'
    )
    updated = models.DateTimeField(default=timezone.now)
    file = models.FileField(upload_to='documents/%Y/%m/%d')

    def save(self, *args, **kwargs):
        ticket_id = Ticket.objects.count()
        if ticket_id == 0:
            self.ticket_id = 1
        else:
            self.ticket_id = ticket_id + 1
        return super(Ticket, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.title


class TicketComment(models.Model):

    post = models.ForeignKey(Ticket, null=True, blank=True)
    name = models.CharField(max_length=50)
    date = models.DateTimeField(default=timezone.now)
    email = models.EmailField()
    body = models.TextField()
    active = models.BooleanField(default=True)

    class Meta:
        def __str__(self):
            return self.name

ticket/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../favicon.ico">

    <title>Blog Template for Bootstrap</title>
    


    <!-- Bootstrap core CSS -->
    
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">


    <script type="text/javascript" src="../../../../static/js/jquery.min.js"></script>
    <script type="text/javascript" src="../../../../static/js/bootstrap.min.js"></script>
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static '/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          <a class="blog-nav-item active" href="{% url 'ticket:list' %}" class="btn btn-primary btn-lg active" role="button"> Home</a>
          <a class="blog-nav-item active" href="{% url 'ticket:pending' %}" class="btn btn-primary btn-lg active" role="button"> <strong>Total Pending Ticket</strong></a>
          <a class="blog-nav-item" href="{% url 'ticket:solved' %}" class="btn btn-primary btn-lg active" role="button"> <strong>Total Solved Ticket</strong></a>
          <a class="blog-nav-item" href="{% url 'ticket:closed' %}" class="btn btn-primary btn-lg active" role="button"> <strong>Total Closed Ticket</strong></a></div>
          <div class= 'pull-right'><a class="blog-nav-item" href="{% url 'ticket:login'%}" class="btn btn-primary btn-lg active" role="button"><strong>Logout</strong></a></div>
           <div class= 'pull-right'><p class="text-danger"><h4><p class="text-danger"><strong>Welcome {{user}}</strong></p> </h4></p></div>
          <a class="blog-nav-item" href="#"></a>
          <a class="blog-nav-item" href="#"></a>
          <br>
          <br>
        </nav>
      </div>
    </div>

    <div class="container">
    <div class="masthead">
        
        <nav>
          <ul class="nav nav-justified">
           </ul>
        </nav>
      </div>
     {% if messages %}
      <div class ="row">
          <div class='col-xs-25'>
            {% for message in messages %}
            <p>{% if message.tags %} {% endif %}<p class="bg-primary">
             <div class="alert alert-success" role="alert"><h4>
             <center>{{message}}</center></h4></div>
           {% endfor %}
          </div>
      </div>
      {% endif %}


         
      
      <div class="blog-header">
      {% block title %}
        
      {% endblock %}
      </div>
      <div class="row">

        <div class="col-ms-8 blog-main">
           {% block content %}
           
           {% endblock %}
        </div> 
      </div> 
      </div>
       <footer class="footer">
        <p class="text-center">&copy;Green Design Labs.</p>
        
      </footer>

ticket/templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <!-- <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"> -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <!-- <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="signin.css" rel="stylesheet"> -->
    <link href="{% static 'css/signin.css' %}" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <!-- <script src="{% static '/js/ie-emulation-modes-warning.js' %}"></script> -->
    <script src="{% static '/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
           
           

  </head>

  <body>

    <div class="container">

      {% if form.errors %}
      <center><p class="text-danger">Sorry! Your username and password didn't match. Please try again.</p></center> 
      
      {% endif %}
        
      <form class="form-signin" role="form" method="post" id="login_form" action=""> 
        {% csrf_token %}
          
        <h2 class="form-signin-heading">Please Sign in</h2>
        <label for="username" class="sr-only">username</label>
        <input type="text" id="username" name="username" class="form-control" placeholder="enter your user name" required autofocus>

        <label for="password" class="sr-only">Password</label>
        <input type="password" id="password" name="password" class="form-control" placeholder=" enter your Password" required>
                <!-- <div class="checkbox">
          <label>
            <input type="checkbox" value="remember-me"> Remember me
          </label>
        </div> -->
        <button class="btn btn-lg btn-primary btn-block" type="submit" value="login" >Sign in</button>
      </form>

    </div> <!-- /container -->


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <!-- <script src="{% static '/js/ie-emulation-modes-warning.js' %}"></script> -->
    <script src="{% static '/js/ie10-viewport-bug-workaround.js' %}"></script>
    
    
      <a href= "{% url 'ticket:register' %}"><center><h4>register user</center></h4></a>
  

  </body>
</html>

ticket/templates/base2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../favicon.ico">

    <title>Blog Template for Bootstrap</title>
    


    <!-- Bootstrap core CSS -->
    
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="{% static 'css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">


    <script type="text/javascript" src="../../../../static/js/jquery.min.js"></script>
    <script type="text/javascript" src="../../../../static/js/bootstrap.min.js"></script>
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="{% static '/js/ie-emulation-modes-warning.js' %}"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="blog-masthead">
      <div class="container">
        <nav class="blog-nav">
          
          <a class="blog-nav-item" href="#"></a>
          <a class="blog-nav-item" href="#"></a>
        </nav>
      </div>
    </div>

    <div class="container">
    <div class="masthead">
        
        <nav>
          <ul class="nav nav-justified">
            
            <!-- <li><a href="#"><a href="http://127.0.0.1:8000/blog/rag/">contact us</a></li> -->
            
            <!-- <li><a href="#"><a href= 'http://127.0.0.1:8000/blog/1/mod/'>Add Ticket</a></a></li>
             -->
            
            
          </ul>
        </nav>
      </div>

    <div class="blog-header">
      {% block title %}
        
      {% endblock %}
      </div>
      <div class="row">

        <div class="col-ms-8 blog-main">
           {% block content %}
           
           {% endblock %}
        </div> 
      </div> 
      </div>
       <footer class="footer">
        <p class="text-center">&copy;Green Design Labs.</p>
        
      </footer>

ticket/templates/closed.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}
  <center><p class="text-danger">Total Closed Tickets Count :</p>
  <span class="badge">{{count}}</span></a></center>
   <hr>
  <table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
 <thead>
  <tr>
    <th><center>Title of the ticket</center></th>
    <th><center>Created on </center></th>
    <th><center>Created_by </center></th>
    <th><center>Ticket id </center></th>
    <th><center>status</center></th>
    <th><center>Body of ticket</center></th>
    <th><center>Check the detail</center></th>
  </tr>
</thead>
<tbody>
   {% for ticket in closed_tickets %}
  <tr>

    <td class="active">{{ticket.title}}</td>
    <td class="info">{{ticket.created}}</td>
    <td class="warning">{{ticket.created_by}} </td>
    <td class="success">{{ticket.ticket_id}} </td>
    <td class="active">{{ticket.status}}</td>
    <td class="warning">{{ticket.body}}</td>
    <td class="warning"><a href="{% url 'ticket:detail' pk=ticket.id %}">View Detail</a></td>

    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

ticket/templates/hello.html
<hello world>

ticket/templates/logged_out.html
{% extends 'base2.html' %}
{% load staticfiles %}
{% block title %}
{% endblock %}
{% block content %}
<hr>
</hr>
<ul class="list-group">
  <li class="list-group-item list-group-item-success"><h1><center><h4>You are logged out Succesfully</h4></center></h1>
</li>
<hr>

<center><a href="{% url 'ticket:login'%}" class="btn btn-primary btn-lg active" role="button">Please Login</a></center>
</a>
</hr>
<hr>
</hr>

{% endblock %}

ticket/templates/pending.html
{% extends 'base.html' %}
{% block content %}

    <div class='container'>
      <ol class='breadcrumb'>
        <li><a href="{% url 'ticket:list' %}">list</a>
        <li><a href="{% url 'ticket:pending' %}">pending</a>
        </li>
        </li>
      </ol>
    </div> 

	<center><p class="text-danger">Total Pending Tickets Count :</p>
	<span class="badge">{{count}}</span></a></center>
  	
  	<hr>
  <table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
	<thead>
  	<tr>
    <th><center>Title of the ticket</center></th>
    <th><center>Created on </center></th>
    <th><center>Created_by </center></th>
    <th><center>Ticket id </center></th>
    <th><center>status</center></th>
    <th><center>Body of ticket</center></th>
    <th><center>Check the detail</center></th>
  	</tr>
	</thead>
	<tbody>
   	{% for ticket in pending_tickets %}
  	<tr>
    <td class="active">{{ticket.title}}</td>
    <td class="info">{{ticket.created}}</td>
    <td class="warning">{{ticket.created_by}} </td>
    <td class="success">{{ticket.ticket_id}} </td>
    <td class="active">{{ticket.status}}</td>
    <td class="warning">{{ticket.body}}</td>
    <td class="warning"><a href="{% url 'ticket:detail' pk=ticket.id %}">View Detail</a></td>
   	</tr>
    {% endfor %}
    </tbody>
	</table>
	{% endblock %}

ticket/templates/solved.html
{% extends 'base.html' %}
{% block title %}
{% endblock %}
{% block content %}
  <center><p class="text-danger">Total Solved Tickets Count :</p>
  <span class="badge">{{count}}</span></a></center>
   <hr>
  <table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
<thead>
  <tr>
    <th><center>Title of the ticket</center></th>
    <th><center>Created on </center></th>
    <th><center>Created_by </center></th>
    <th><center>Ticket id </center></th>
    <th><center>status</center></th>
    <th><center>Body of ticket</center></th>
    <th><center>Check the detail</center></th>
  </tr>
</thead>
<tbody>
   {% for ticket in solved_tickets %}
  <tr>

    <td class="active">{{ticket.title}}</td>
    <td class="info">{{ticket.created}}</td>
    <td class="warning">{{ticket.created_by}} </td>
    <td class="success">{{ticket.ticket_id}} </td>
    <td class="active">{{ticket.status}}</td>
    <td class="warning">{{ticket.body}}</td>
    <td class="warning"><a href="{% url 'ticket:detail' pk=ticket.id %}">View Detail</a></td>

    </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

ticket/templates/testing.html
{{foo}}

ticket/templates/ticket_detail.html
{% extends 'base.html' %}

{% block title %}
{% endblock %}
{% block content %}
    <div class='container'>
      <ol class='breadcrumb'>
        <li><a href="{% url 'ticket:list' %}">List</a>
        <li><a href="{% url 'ticket:detail' pk=post.id %}">Detail</a>
        </li>
        </li>
      </ol>
    </div>

  <br>

<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-12">
  <!-- Ticket Deatil  starts from here-->
    <div class="panel panel-primary">
  <div class="panel-heading">Ticket Information</div>
  <div class="panel-body">

   <div class="row">
        <div class="col-lg-6">
            <label for="reel_type">Title of Ticket</label>
                <input  class="form-control" id="reel_type" type="text" name="reel_type" value="{{post.title}}" readonly>
            <label for="rm_type">Body of Ticket</label>
                <input  class="form-control" id="rm_type" type="text" name="rm_type" value="{{post.body}} " readonly>
                

            <label for="rm_type">Created by</label>
                <input  class="form-control" id="rm_type" type="text" name="rm_type" value="      {{post.created_by}} " readonly>
                </div>
                <div class="col-lg-6">
            <label for="rm_type">Created on</label>
                <input  class="form-control" id="rm_type" type="text" name="rm_type" value="      {{post.created}} " readonly>
            <label for="rm_type">Ticket id</label>
                <input  class="form-control" id="rm_type" type="text" name="rm_type" value="      {{post.ticket_id}} " readonly>
            <label for="rm_type">status</label>
                <input  class="form-control" id="rm_type" type="text" name="rm_type" value="      {{post.status}} " readonly> 
        </div>
      </div>
            <strong>image:</strong></strong> <img src="{{post.file.url}}" alt="image" Width="6000">                   
       <form action="{% url 'ticket:update' pk=post.id %}" method="post">
        {{form1.as_p}}
        {% csrf_token %}
        <p><button type="submit" class="btn btn-success">update</button>
       </form>
</div>
         <!-- End Ticket Deatil -->
  </div>
</div>
<!-- comment modal box starts from here -->
<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-12">
      <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#comment">
      Add Comment</button>

<div class="modal fade" id="comment" tabindex="-1" role="     dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="  modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Adding  Comment</h4>
      </div>
      <div class="modal-body">
           <p> <form action="{% url 'ticket:comment' pk=post.id %}"  method="post">
           {{form.as_p}}
           {% csrf_token %}</p>
           <p><button type="submit" class="btn btn-success">Submit</button></p>
           </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
</div>
  </div>
  <!-- comment modal ends here -->
    <hr>
    <!-- comments from users starts from here -->
<div class="row">
  <div class="col-sm-12 col-md-12 col-lg-12">
    <div class="panel panel-primary">
      <div class="panel-heading">Comments From Users</div>
      <div class="panel-body">
        {% for comment in post.ticketcomment_set.all %}
          <hr>
         <h1 style="font-size:80%;">Name of the User :<strong> {{comment.name}}</strong></h1>
         <h2><p><strong><h2 style="font-size:80%;"user comment:</strong> <mark>{{comment.body}}</mark></p></h2><small> {{comment.date}}</small>
         </hr>
          {% endfor %}
    </div>
  </div>
</div>
  </hr>
  <!-- comments from users ends here -->
  
{% endblock %}

    
    

ticket/templates/ticket_list.html
{% extends 'base.html' %}
{% block title %}

<link href="../../../../static/css/bootstrap.min.css" rel="stylesheet">
<link href="../../../static/css/dataTables.bootstrap.min.css" rel="stylesheet">
{{date}}       
    <!-- displaying pedning,totatl,closed tickets starts from here -->
     <div class="col-lg-2 col-md-2 col-sm-2 pull-right">
     <ul class="list-group">
      <li class="list-group-item">
        <span class="badge">{{total_ticket}}</span>
        <p class="text-danger">Total Tickets:</p>
        </li>
      <li class="list-group-item">
        <span class="badge">{{pending_count}}</span>
        <p class="text-info">Pending Tickets:</p> 
      </li>
      <li class="list-group-item">
        <span class="badge">{{solved_count}}</span>
        <p class="text-warning">Solved Tickets:</p> 
      </li>
      <li class="list-group-item">
        <span class="badge">{{closed_count}}</span>
        <p class="text-success">Closed Tickets:</p> 
      </li>
    </ul>
    </div>
      <!-- displaying pedning,totatl,closed tickets ends here -->

  {% endblock %}
  {% block content %}
 <!-- modal for add ticket starts from here -->
<button type="button" class="btn btn-info btn-lg" data-toggle="modal" data-target="#myModal">Add Ticket</button>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Adding Ticket</h4>
      </div>
      <div class="modal-body">

        <p> <form  method="post" action="." enctype="multipart/form-data">
           {{form.as_p}}
           {% csrf_token %}</p>
           <p><button type="submit" class="btn btn-success">Submit</button></p>
           </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
   <!-- modal for add ticket ends  here -->
<hr>
   
   <!-- list(table) of tickets start from here -->
<table id="example" class="table table-striped table-bordered" width="100%" cellspacing="0">
<thead>
  <tr>
    <th><center>Title of the ticket</center></th>
    <th><center>Created on </center></th>
    <th><center>Created_by </center></th>
    <th><center>Ticket id </center></th>
    <th><center>status</center></th>
    <th><center>Body of ticket</center></th>
    <th><center>Check the detail</center></th>
  </tr>
</thead>
<tbody>
  {% for post in posts %}
  <tr>
    <td class="danger">{{post.title}} </td>
    <td class="info">{{post.created}}</td>
    <td class="warning">{{post.created_by}} </td>
    <td class="success">{{post.ticket_id}} </td>
    <td class="active">{{post.status}}</td>
    <td class="warning">{{post.body}}</td>
    <td class="warning"><a href="{% url 'ticket:detail' pk=post.id %}">View Detail</a></td>
  </tr>
    {% endfor %}
  </tbody>
</table>
   <!-- list(table) of tickets ends here -->
   
    <hr>
      </div>
      </hr>
      <script type="text/javascript" src="../../../../static/js/jquery-1.12.3.js"></script>
      <script type="text/javascript" src="../../../../static/js/dataTables.bootstrap.min.js"></script>
      <script type="text/javascript" src= "../../../../static/js/jquery.dataTables.min.js"></script>

   <!-- this is jquery code for pagination -->
<script>
$(document).ready(function() {
  $('#example').DataTable();
} );
</script>
</hr>      
{% endblock %}
  <!-- jquery code for pagination ends here-->